services:
  # OTEL Collector - Metrics ve traces toplar
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.135.0
    container_name: otel-collector
    restart: unless-stopped
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8889:8889"   # Prometheus metrics scraping
    volumes:
      - ./config/otel-collector.yml:/etc/otelcol-contrib/otel-collector-config.yml
    command: ["--config=/etc/otelcol-contrib/otel-collector-config.yml"]
    networks:
      - monitoring
      - app-network

  # Prometheus - Metrics storage
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.retention.time=15d"
    networks:
      - monitoring

  # Tempo - Tracing storage
  tempo:
    image: grafana/tempo:2.8.2
    container_name: tempo
    restart: unless-stopped
    ports:
      - "3200:3200"   # Tempo HTTP API
      - "9095:9095"   # Query Frontend
      - "7946:7946"   # Memberlist
    volumes:
      - ./config/tempo.yml:/etc/tempo/tempo.yml
      - tempo-data:/var/tempo
    command: [ "-config.file=/etc/tempo/tempo.yml" ]
    networks:
      - monitoring

  # Loki - Log aggregation
  loki:
    image: grafana/loki:3.5.5
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"   # HTTP
    volumes:
      - ./config/loki.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  # Grafana - Visualization
  grafana:
    image: grafana/grafana:12.1.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - monitoring
    depends_on:
      - prometheus
      - tempo
      - loki

networks:
  monitoring:
    driver: bridge
  app-network:
    external: true
    name: goboilerplate_app-network

volumes:
  prometheus-data:
  grafana-data:
  tempo-data:
  loki-data: