groups:
  - name: goauthboiler_alerts
    rules:
      - alert: ApplicationDown
        expr: up{job="goauthboiler-app"} == 0
        for: 1m
        labels:
          severity: critical
          service: goauthboiler
        annotations:
          summary: "GoAuth Boilerplate application is down"
          description: "The GoAuth Boilerplate application has been down for more than 1 minute."

      - alert: HighErrorRate
        expr: rate(http_requests_total{status_code=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
          service: goauthboiler
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second on {{ $labels.endpoint }}"

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 3m
        labels:
          severity: warning
          service: goauthboiler
        annotations:
          summary: "High response time"
          description: "95th percentile response time is {{ $value }}s"

      - alert: HighAuthFailureRate
        expr: rate(auth_attempts_total{status="failed"}[5m]) > 5
        for: 1m
        labels:
          severity: warning
          service: goauthboiler
        annotations:
          summary: "High authentication failure rate"
          description: "Authentication failure rate is {{ $value }} failures per second"

      - alert: LowCacheHitRatio
        expr: rate(cache_hits_total[5m]) / (rate(cache_hits_total[5m]) + rate(cache_misses_total[5m])) < 0.7
        for: 5m
        labels:
          severity: warning
          service: goauthboiler
        annotations:
          summary: "Low cache hit ratio"
          description: "Cache hit ratio is {{ $value | humanizePercentage }} for {{ $labels.cache_type }}"

      - alert: DatabaseConnectionsHigh
        expr: database_connections_active > 20
        for: 2m
        labels:
          severity: warning
          service: goauthboiler
        annotations:
          summary: "High number of database connections"
          description: "Database has {{ $value }} active connections"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.8
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanizePercentage }}"

      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%"
